[project]
authors = ["DarthTimothee <timoverlaan@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "scAGG"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
