[project]
authors = ["DarthTimothee <timoverlaan@gmail.com>"]
channels = ["nvidia", "conda-forge", "pytorch", "bioconda", "pyg"]
description = "scAGG: Sample-level embedding and classification of Alzheimer's disease from single-nucleus data"
name = "scAGG"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[system-requirements]
linux = "3.10"
cuda = "12.4"

[dependencies]
pytorch = {version=">=2.4.1,<3", channel="pytorch"}
torchvision = {version=">=0.19.1,<1", channel="pytorch"}
torchaudio = {version=">=2.4.1,<3", channel="pytorch"}
pytorch-cuda = "12.4.*"
pyg = ">=2.6.1,<3"
scanpy = ">=1.10.3,<2"
ipykernel = ">=6.29.5,<7"
scikit-learn = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
pytorch-sparse = ">=0.6.18,<0.7"
